Basic Programs Added
chandrakant100/JAVA_PROGRAMS pull request #9
Opened 2020-10-07 04:06 UTC by extrathings

- Leap Year
- Sum of Array Elements
- Linear Search
- Reverse of A Number

2020-10-07 10:19 UTC, chandrakant100 requested changes

2020-10-07 10:19 UTC, chandrakant100 commented on assignment3/LeapYear.java
> +import java.util.Scanner;
Add some comments in bullet points describing your approach.

2020-10-08 03:23 UTC, extrathings commented
Done!!

2020-10-08 04:41 UTC, chandrakant100 approved these changes

2020-10-08 04:41 UTC, chandrakant100 commented
> Done!!

`GOOD JOB!!!`

2020-10-08 04:42 UTC, merged